### ISSUE TITLE
Error message when loading segmentation data

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#104]
When reviewing some tracer segmentations, I receive this error message (below). I have tried in both v0.3.1 and v0.2.18, and encountered the same issue. I notice that one of the following three scenarios happens: 1) it works as expected, 2) it opens the segmentation data but expected 'done' information is not retained, and 3) error message and cannot open the segmentation file. I will send the files I used when encountering the error message:

![image](https://user-images.githubusercontent.com/3201990/111809095-ff102c80-88aa-11eb-955c-09bf559986f8.png)

**Comment by davidborland** [comment]
Believe the issue was incorrect renaming of a .nii.json file as a .nii file. Closing for now.
