### ISSUE TITLE
Checking JSON files

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#107]
Hi @davidborland,

I am not always seeing consistent count information in the .json files. Not sure if this is a saving issue or if it's something in the .json itself. Attached are the files in which I expected to see 38 'done' nuclei. I used v0.3.2 when reviewing the segmentations.

[Ashley1.zip](https://github.com/RENCI/Segmentor/files/6216284/Ashley1.zip)

**Comment by davidborland** [comment]
Just pushed a fix for this that will be in the next release.
