### ISSUE TITLE
Enhancing Feedback for Training Purposes

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#111]
Presently, training feedback is provided by unchecking 'done' for traced nuclei. Adding the following columns to the Region Table with checkboxes will help provide more detailed feedback:

- Undertraced
- Overtraced
- Add New Region
- Remove Existing Region

These columns would be a 'first part' of this enhancement request and would be great to incorporate with several ninjas-in-training this week. The second part is a longer term request for the ability to provide additional text annotations (like a comment appended to a nucleus ID). This could be especially useful for training modules or future developments.

**Comment by davidborland** [comment]
Adding 4 more columns might make the region table a bit too big on smaller displays. We could potentially switch out some of the other columns when in "training feedback mode". Are there any columns that would be less useful in this mode?

Alternately we could keep the width of the region table fixed, and add a horizontal scrollbar to show more columns.

Any other ideas?

**Comment by davidborland** [comment]
@JustKeepClimbing, just wanted to make sure you saw the comment above.

**Comment by JustKeepClimbing** [comment]
Is a pop-out window possible which would include only the following? ID | Undertraced | Overtraced | Add to Slice | Remove ID

Maybe we can add 'Training' as an additional dropdown heading, and when the user checks 'Feedback' in the dropdown, the pop-out window with feedback appears. What do you think?

**Comment by JustKeepClimbing** [comment]
I would also like to add one more option to the pop-out window: Correct from Split / Merge, since there are occasional regions that I split / merge for a ninja-in-training that s/he later corrects.

**Comment by davidborland** [comment]
I think that seems reasonable.

**Comment by davidborland** [comment]
Initial version implemented
