### ISSUE TITLE
Check holes for done regions

### ISSUE THREAD

**Issue by davidborland** [RENCI/Segmentor#113]

**Comment by davidborland** [comment]
Currently only checking that the region is contiguous.

**Comment by davidborland** [comment]
Implemented

**Comment by JustKeepClimbing** [comment]
hi @davidborland , when reviewing masks, I still notice missing pixels in some refined masks. As a quick test, I used the 'add new region' to create a mask and added a voxel-sized hole in it. I was able to mark the nucleus as 'done.'

**Comment by davidborland** [comment]
The way it is currently implemented, if you just create a region with just a single slice, holes would still be allowed. However if you have a region with 3 or more slices, any holes in the interior slices should not be allowed.

**Comment by davidborland** [comment]
Allowed:

![image](https://user-images.githubusercontent.com/289957/127005348-2ad9569f-04a7-4b1f-b84d-1b5cfdf75405.png)

**Comment by davidborland** [comment]
Not allowed:
![image](https://user-images.githubusercontent.com/289957/127005569-b08d05a2-0ea5-438a-8293-22e492a87d42.png)

**Comment by JustKeepClimbing** [comment]
Oh, I see! Ok, that should be fine. What I tested only had two slices, so this is good to know. : )

**Comment by davidborland** [comment]
Sure thing. Let me know if you do see any problems.
