### ISSUE TITLE
Training Feedback Table Enhancements

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#115]
Brainstormed with @talafar and @carlaesc after several mask reviews for additional enhancements to the Feedback Dialog box:
• Add 'Count' to the right of filter checkbox (to verify that IDs match number of Region Table suggested edits)
• Add these table headers: 'Smooth 3D Profile,' 'Fill Holes,' 'Add New ID'
• Add tool tip descriptions for each table header
• Add comment section to provide additional context for split / merge suggestions (e.g. 'Merge nucleus 35 with nucleus 25')
• Add Search bar to type in an ID
• Add shortcut key for feedback table (e.g., 'f')
• Link Feedback Dialog IDs to Region Table and segmentations
• Suggestions for reviewing masks to enhance version control:
- Add column for 'Complete' when a 'done' nucleus needs no further corrections
- Add column for 'Reviewing' to show in-process reviews for a given week
- Add timestamp next to feedback

We can break this issue up into smaller ones if needed.

**Comment by davidborland** [comment]
Turned into a checklist:

- [ ] Add 'Count' to the right of filter checkbox (to verify that IDs match number of Region Table suggested edits)
- [ ] Add these table headers: 'Smooth 3D Profile,' 'Fill Holes,' 'Add New ID'
- [ ] Add tool tip descriptions for each table header
- [ ] Add comment section to provide additional context for split / merge suggestions (e.g. 'Merge nucleus 35 with nucleus 25')
- [ ] Add Search bar to type in an ID
- [ ] Add shortcut key for feedback table (e.g., 'f')
- [ ] Link Feedback Dialog IDs to Region Table and segmentations

Suggestions for reviewing masks to enhance version control:
    - [ ] Add column for 'Complete' when a 'done' nucleus needs no further corrections
    - [ ] Add column for 'Reviewing' to show in-process reviews for a given week
    - [ ] Add timestamp next to feedback

**Comment by davidborland** [comment]
Question: Is it useful to have multiple columns with checkboxes for different feedback options, or would it be easier to just have the comment section where you can type?

**Comment by davidborland** [comment]
Can you supply the tooltip text you would like for each header?

**Comment by davidborland** [comment]
What do you mean by "Link Feedback Dialog IDs to Region Table and segmentations"

**Comment by davidborland** [comment]
Revisions after discussion on 07/27/2021:

- [ ] Reformat feedback table to have only id, comment, and done columns.
- [ ] Change done to a tri-state checkbox in both tables. Need to discuss proper terminology - pending vs. confirmed?
- [ ] Add pop-up of comment text on mouseover. Maybe in the scene, maybe as a tooltip in the region table.
- [ ] Add Ctrl-f shortcut for feedback table.
- [ ] Add id search box for both tables.

**Comment by JustKeepClimbing** [comment]
For tri-state checkbox, can we use 'Ninja Done' and 'Sensei Done?' The first implies that the ninja has refined the nucleus and the second implies it has be 'expert reviewed.' What do you think?

**Comment by davidborland** [comment]
From the standpoint of the UI, we just need a single term for the column. Could potentially stay with "Done" for that. 

I'm not sure where else we would need the terms for the three states. Maybe we could add a tooltip to the checkbox with that? In that case I might stay away from "ninja" and "sensei", in case outside groups might use the tool. Could maybe go with "refined" and "reviewed" for those?

What do you think?

**Comment by JustKeepClimbing** [comment]
'Refined' and 'Reviewed' work well! Does the third state have a name, or would a null state imply that the state is 'not yet refined?' Not having a name for the third state makes sense to me, but I'm open to what you think is best.

**Comment by davidborland** [comment]
Yeah, it would basically be the same as now...not done/refined/reviewed. Maybe "incomplete" or "unrefined"?

**Comment by JustKeepClimbing** [comment]
Can we use 'To Edit?' It's fewer characters and distinguishes from the 'Refining' column you already have.

**Comment by davidborland** [comment]
Implemented
