### ISSUE TITLE
"Done" Filter Not Working

### ISSUE THREAD

**Issue by talafar** [RENCI/Segmentor#125]
I am using the latest version (v0.4.2) and when I tried to toggle on 'done' in the main table so that all the done nuclei were shown on top, it did not work. I have attached a screen recording to help show what I mean.

https://user-images.githubusercontent.com/67338660/132918946-ba034c93-bb2a-409b-9b6b-4a3713f724b6.mov

**Comment by davidborland** [comment]
I will look into this

**Comment by davidborland** [comment]
Fixed in v0.4.3
