### ISSUE TITLE
Solid Overlay Issue

### ISSUE THREAD

**Issue by jadehardwick** [RENCI/Segmentor#130]
![image](https://user-images.githubusercontent.com/55506686/134417802-f555c738-2723-46e6-b9d2-be74e4d36a04.png)
In most recent update, the solid overlay option remains gray even for nuclei that are not finished yet. These nuclei do not have the "done" or "verified" options checked. Toggling the solid overlay on and off does not fix their color, but the outline overlay is the correct color. In the image, the same layer is displayed on in the 3D and 2D views. The 3D view and side bar indicate that all the nuclei in this layer should be colored, but they are all gray.

**Comment by davidborland** [comment]
Can you send me the image file, segmentation file, and segmentation json file you are using?

**Comment by davidborland** [comment]
@jadehardwick , just wanted to make sure you saw my comment above.

**Comment by davidborland** [comment]
Looks like this was an issue when loading old (pre v0.4.3) json files, which didn't contain verified info, into v0.4.3. I've fixed the problem, which will be in the next release.

Note: you should be able to manually toggle the Done status to fix the problem for a given nucleus in the meantime.
