### ISSUE TITLE
Add shortcut keys to access feedback table and verifying completed labels

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#133]
Adding two shortcut keys (1) for accessing and hiding the feedback table and 2) being able to toggle on the verify checkbox in the feedback table) would be very helpful during mask reviews! Open to whatever you think is appropriate to represent these two shortcut keys.

**Comment by davidborland** [comment]
How would the region be determined for toggling the verified checkbox? The current region? The region for the row the mouse is currently over? Other?

**Comment by davidborland** [comment]
Implemented
