### ISSUE TITLE
Adding feature for dense 'nearest neighbor' nuclei

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#139]
For particularly dense images, many nuclei appear when using the neighboring nuclei filter. Can we add an additional visibility feature to only filter to nuclei directly contacting the current region? For the existing filter, some of the nuclei that appear are not relevant visually when providing feedback. Picture below as an example:
![Nearest Neighbors Example](https://user-images.githubusercontent.com/3201990/142901758-f95bf306-c332-43dd-955b-f7ef585a7531.png)

**Comment by davidborland** [comment]
Remember that you can manually turn on and off visibility for any region by entering Region Visibility mode and clicking the regions you want to turn on/off.

Beyond that, we could add a user control for the radius used to count as a neighbor, and put it in settings. What do you think @JustKeepClimbing ?

**Comment by JustKeepClimbing** [comment]
Hi @davidborland , sorry for the delay in responding. I recall the visible toggle, but having a more advanced control to define radius would be helpful with denser images. This may be a moot point though as Segmentor evolves.

**Comment by davidborland** [comment]
Initial version of neighbor radius control, and improved method for calculating neighbor distance implemented.
