### ISSUE TITLE
GUI layout: default features when opening Segmentor

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#65]
Tracers more frequently trace without surface normals selected. Can we adjust the default selection to be 'unselected' for the toggle surface normal tool?

Related, can we add a default toggle checkbox for the top panel, such that the top panel is visible when opening Segmentor, but hidden if unchecked?

Please see attached screenshot.

![GUIlayout- 2020-06-30](https://user-images.githubusercontent.com/3201990/86176686-4e32e900-baf3-11ea-81c0-9692e587411f.png)

**Comment by davidborland** [comment]
I think this isn't needed anymore with the upcoming changes to the top panel. We can reopen if need be.
