### ISSUE TITLE
Add Dice score analysis to Segmentor interface

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#83]
Presently, tracers are trained and evaluated using a Dice score analysis that requires a manual process to run an R script. Allowing tracers to run Dice score analyses within Segmentor will streamline the pipeline for providing training feedback.

[Attached](https://drive.google.com/drive/folders/1hN3evuazQUMYhk0lZqEXdUiKgbLnqydE?usp=sharing) are the StandardMask (.nii and .nii.gz), Training Image (.nii), Dice score R script, and helpful ITK resources for implementing a Dice score analysis within Segmentor:

https://itk.org/Doxygen/html/classitk_1_1LabelOverlapMeasuresImageFilter.html
https://www.insight-journal.org/browse/publication/707
https://www.insight-journal.org/download/viewpdf/707/2/download

**Comment by davidborland** [comment]
This has been added to the website, so I think it should be closed.
