### ISSUE TITLE
Clear 'modified' checkmark once region marked 'done'

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#84]
I came across this observation while working on the Segmentor paper figures. Presently, a region can be simultaneously 'modified' and 'done.' This makes it possible for the total count to be 'less' than the sum of the 'done' and 'modified' counts. Creating a means to turn off the 'modified' checkmark when 'done' is checked will help alleviate potential confusion about how many regions were modified in a given work session. The picture below highlights region 32, which is marked 'modified' and 'done.'

![image](https://user-images.githubusercontent.com/3201990/99301362-da804700-281b-11eb-8721-2d884ea76d2a.png)

**Comment by davidborland** [comment]
Does it make sense to change "Modified" to "Active" or something similar?

**Comment by JustKeepClimbing** [comment]
@davidborland Thanks for reminding me about this comment! When I initially wrote this, I think we ought to have a 'flag' such that a nucleus can be 'modified' or 'done,' but not 'modified and done.' Modified still works as the term. Can we update in a way such that when clicking 'done,' the modified icon does not appear in the row and no longer counts toward the modified count. Modified + Done should equal total count, which is helpful in terms of assessing tracing progress -- what do you think?

**Comment by davidborland** [comment]
Yeah, we can update the logic as you suggest. I was just wondering if we should use a different term than modified if we do that, as a done region has most likely been modified. Maybe "active" or "in progress". I'm fine either way though.

**Comment by JustKeepClimbing** [comment]
Sounds like we can use 'refining' as a way to suggest that manual tracing (refinement) is happening. Thanks, I think this addresses  my comments!

**Comment by davidborland** [comment]
Implemented
