### ISSUE TITLE
Mac download for v0.2.18

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/Segmentor#89]
A new tracer e-mailed me stating that he keeps encountering errors message every time he tries to download Segmentor through the Nuclei Ninja website. Here are some things that we verified and tried:

- He verified that his security settings allow for external application downloads.
- I pointed him to the Mac installation instructions on the Wiki page (no successful download after trying).

Attached is a screenshot he sent me with the error message.
<img width="874" alt="Screen Shot 2021-01-24 at 6 32 55 PM" src="https://user-images.githubusercontent.com/3201990/105718156-f0327c80-5eee-11eb-9706-983ba975367c.png">

**Comment by davidborland** [comment]
What version of OSX is he using?

**Comment by JustKeepClimbing** [comment]
Hi @mihikaik , can you comment on your Mac version here?

**Comment by mihikaik** [comment]
Version 10.13.6. Could my operating system be causing an issue? Just realized there is a new version 11.0.

**Comment by mihikaik** [comment]
Looks like dylib was built for version 10.15. I'll go ahead and update my OS and see how it goes.

**Comment by davidborland** [comment]
Ok. Try that and let me know how it goes.

**Comment by mihikaik** [comment]
Updating the system software fixed the issue. Thanks for your help

**Comment by davidborland** [comment]
Great!
