### ISSUE TITLE
Application Crashing on Mac

### ISSUE THREAD

**Issue by talafar** [RENCI/Segmentor#90]
At random times the application will crash while I am tracing. It has been happening for a while now with all the versions and I've tried to work around it, but it is now becoming very annoying because I will be in the middle of working on the nucleus and it crashes and doesn't save that work. I am on the most current version (18) and it seems the issue has become worse compared to version 17.

**Comment by davidborland** [comment]
Sorry to hear that. If you can provide any more details on what specific operations you were performing leading up to the crash(es), I can try to look into it.

**Comment by talafar** [comment]
Hey, David! In the most recent versions (16-18), the crashes weren't really caused by a specific operation; I am usually just tracing and it suddenly crashes, resulting in lost work. When I first started tracing (version 12 or 13), I noticed it would crash when I pressed redo/undo a couple times, so I stopped using those functions entirely to avoid the crashing. Other people with Macs on the team have also experienced these crashes. I'm sorry I couldn't be of much help explaining, but if it would be useful I can screen record from the moment I open the application to when it crashes? Let me know if you want me to do that.

**Comment by davidborland** [comment]
That would be useful, thanks. I'll also look into logging user interactions to a file which should help in debugging these types of problems.

**Comment by davidborland** [comment]
Can you let me know the specs on the computer you are using (mostly care about RAM)?

**Comment by talafar** [comment]
<img width="572" alt="Screen Shot 2021-02-01 at 4 57 14 PM" src="https://user-images.githubusercontent.com/67338660/106523045-901f7580-64ae-11eb-8a18-2e7985bdf18a.png">

**Comment by talafar** [comment]
I've uploaded a picture that shows all my computer's specifications

**Comment by davidborland** [comment]
Thanks. Specs look good.

**Comment by talafar** [comment]
[https://drive.google.com/file/d/197Ahx7-4YuFIEDeLKhHhdMAIi9Otodt3/view?usp=sharing](url)

I finally caught a crash on recording! The url will take you to the 25 minute video showing from the moment I opened the image and segmentation to when it crashed.

**Comment by talafar** [comment]
Prior to this crash, it happened twice within the hour. I have a theory that they happen when working on nuclei near the edges of images (this is based the 3 times it happened recently).

**Comment by davidborland** [comment]
Ok, thanks. I'll take a look.

**Comment by davidborland** [comment]
@talafar can you also send me the input data you were using (image fileand segmentation/json file if any) for this? You can just slack it to me. Thank.

**Comment by davidborland** [comment]
Hey @talafar, I'm looking into this some more now. I noticed that you were editing in the 3D view at the edge of the volume when the crash happened. Is that normal, or does it also happen in other situations?

**Comment by davidborland** [comment]
@talafar I think I fixed this in the most recent release (v0.3.0). It was due to the 3D highlight circle which could cause the program to try to lookup data outside of the volume.
