### ISSUE TITLE
Scroll Bar on Windows Segmentor Application 

### ISSUE THREAD

**Issue by cmainz02** [RENCI/Segmentor#93]
The bar to scroll over to brush radius is blocking the up and down arrows to increase/decrease the radius on the Windows version of Segmentor. Even in fullscreen, the issue does not resolve.

**Comment by davidborland** [comment]
Can you post a screenshot? What resolution is your monitor?

In the meantime, be aware that you can use Ctrl + left / right arrow to change the brush radius.

**Comment by cmainz02** [comment]
<img width="960" alt="error 1" src="https://user-images.githubusercontent.com/77849284/107713855-bd7bd880-6c91-11eb-87ce-eabc65d37696.PNG">
To be completely honest, I have no idea what the resolution is! Its not a big deal, I can work with it, I just wanted to make sure you knew it was occurring!

**Comment by davidborland** [comment]
If you right-click on the desktop and choose 'Display settings', you should be able to scroll down and see the Display resolution.

If it's happening for you, it might happen for others, so it'd be good to try to fix it.

Does it still happen if you take it of fullscreen / maximize mode and try resizing the height and width of the window?

**Comment by cmainz02** [comment]
1920x1080 is the resolution! 
Even when I make it full screen it is still like that and it will not allow me to adjust the height of the window.

**Comment by davidborland** [comment]
But if you don't make it full screen, and just adjust the window size by hand, does it do the same thing?

**Comment by cmainz02** [comment]
Even when I adjust the window by hand, the size of the toggle bar stays the same
And it cannot adjust is =(

**Comment by davidborland** [comment]
Ok, thanks for the info.

**Comment by JustKeepClimbing** [comment]
@davidborland Just adding that I have also noticed this issue, and it seems to be monitor-dependent. The laptop I'm currently displays Segmentor's GUI as what @cmainz02 shows. I also keep my resolution at 1920x1080 -- interestingly, if I change the scale/layout to less than 150%, that appears to resolve the issue of the sliding bar obscuring the top menu. This is what Segmentor looks like when I change the scale to 100%:
![image](https://user-images.githubusercontent.com/3201990/108262200-9a8a7200-7132-11eb-92f6-ae5e2e1680aa.png)

**Comment by davidborland** [comment]
Yeah, I was poking around a little bit yesterday and saw the same thing regarding the scale/layout. @cmainz02 , if you go into your display properties and set the scale and layout to 100%, do you still have the problem?

![image](https://user-images.githubusercontent.com/289957/108266868-9b260700-7138-11eb-86b0-4ecd26931f93.png)

**Comment by davidborland** [comment]
This should no longer be an issue with the GUI layout changes for the next version. We can reopen if the issue does remain.
